# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Poll')),
            ],
        ),
    ]
